name: Upload Kubeflow Pipelines
on: [push]
jobs:
  kubeflow-job:
    runs-on: self-hosted
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      
      # setup python environment since running on self-hosted mode
      - name: Install Dependencies
        run: |
              python3 --version