name: Upload Kubeflow Pipelines
on: [push]
jobs:
  kubeflow-job:
    runs-on: self-hosted
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      
      # setup python environment since running on self-hosted mode
      - name: Install Dependencies
        run: |
              make setup
      
      - name: Compile KFP
        run: |
              make compile-kfp
      
      - name: Clean Environment
        run: |
              make clean